# EA LSTM :  Evolutionary Attention-based LSTM

![img](../../docs/assets/images/EALSTM.png)

In [1]:
import tensorflow as tf
print(tf.__version__)

2.0.0


In [85]:
class AttentionModule(tf.keras.layers.Layer):
    """
    This layer is the implementation of Simple History attention LSTM
    """
    
    def __init__(self, history_size):
        super(AttentionModule, self).__init__()
        self.history_size = history_size
        
    def build(self, input_shape):
        self.kernel = self.add_weight("kernel", shape=[self.history_size, self.history_size])
        
    def call(self, input_tensor):
        attended_weights = tf.nn.softmax(tf.matmul(input_tensor, self.kernel))
        attended_input = tf.multipy(attended_weights, input_tensor)
        return attended_input
        
        

In [114]:
layer = AttentionModule(3)

In [115]:
input_= tf.random.normal([2,3])
_ = layer(input_)

In [116]:
layer.weights

[<tf.Variable 'attention_module_17/kernel:0' shape=(3, 3) dtype=float32, numpy=
 array([[ 0.59267735,  0.9467783 , -0.8708234 ],
        [ 0.52953553, -0.12709951,  0.9159403 ],
        [-0.6425276 , -0.37680697, -0.12748027]], dtype=float32)>]

In [117]:
_

<tf.Tensor: id=609, shape=(2, 3), dtype=float32, numpy=
array([[0.20666826, 0.12906924, 0.6642626 ],
       [0.35655925, 0.3919982 , 0.25144258]], dtype=float32)>

In [119]:
input_

<tf.Tensor: id=593, shape=(2, 3), dtype=float32, numpy=
array([[-0.01711725,  1.2314945 ,  1.2943593 ],
       [ 0.65963894,  0.53350717,  0.7959399 ]], dtype=float32)>

In [118]:
tf.multiply(_, input_)

<tf.Tensor: id=611, shape=(2, 3), dtype=float32, numpy=
array([[-0.00353759,  0.15894806,  0.8597945 ],
       [ 0.23520036,  0.20913385,  0.20013319]], dtype=float32)>