In [1]:
import os
import sys
import pandas as pd
import csv
import sklearn
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from xgboost import XGBClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, mean_squared_error
from sklearn.preprocessing import Normalizer

In [3]:
data_folder = '../data'
data_files = os.listdir(data_folder)

In [4]:
year_2014 = pd.read_csv(data_folder+'/'+data_files[0])
year_2014.head()

Source Location ID City State Country Latitude Longitude Time Zone  \
0   SUNY       22306    -     -   India    24.65     73.75       5.5   
1   Year       Month  Day  Hour  Minute      DHI       DNI       GHI   
2   2014           1    1     0      30        0         0         0   
3   2014           1    1     1      30        0         0         0   
4   2014           1    1     2      30        0         0         0   

      Elevation Local Time Zone  ... Wind Direction Units Wind Speed  \
0             0             5.5  ...              Degrees        m/s   
1  Clearsky DHI    Clearsky DNI  ...                  NaN        NaN   
2             0               0  ...                  NaN        NaN   
3             0               0  ...                  NaN        NaN   
4             0               0  ...                  NaN        NaN   

  Snow Depth Units Fill Flag 0    Fill Flag 1     Fill Flag 2  \
0                m         NaN  Missing Image  Low Irradiance   
1              NaN         NaN            NaN             NaN   
2              NaN         NaN            NaN             NaN   
3              NaN         NaN            NaN             NaN   
4              NaN         NaN            NaN             NaN   

        Fill Flag 3               Fill Flag 4         Fill Flag 5  Version  
0  Exceeds Clearsky  Missing CLoud Properties  Rayleigh Violation  unknown  
1               NaN                       NaN                 NaN      NaN  
2               NaN                       NaN                 NaN      NaN  
3               NaN                       NaN                 NaN      NaN  
4               NaN                       NaN                 NaN      NaN  

[5 rows x 35 columns]

In [6]:
new_columns = year_2014.iloc[1]
year_all = year_2014[2:]
year_all.columns =new_columns
year = year_all.loc[:, year_all.columns.notnull()]

# for counter,i in enumerate(new_columns):
#     print(i)


year = year.drop(columns=['Year','Month','Day','Minute','Hour','DHI','DNI','Clearsky DHI','Clearsky DNI','Fill Flag'])

In [7]:
year = year.astype('float64')
year.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 8760 entries, 2 to 8761
Data columns (total 11 columns):
GHI                   8760 non-null float64
Clearsky GHI          8760 non-null float64
Dew Point             8760 non-null float64
Temperature           8760 non-null float64
Pressure              8760 non-null float64
Relative Humidity     8760 non-null float64
Solar Zenith Angle    8760 non-null float64
Precipitable Water    8760 non-null float64
Snow Depth            8760 non-null float64
Wind Direction        8760 non-null float64
Wind Speed            8760 non-null float64
dtypes: float64(11)
memory usage: 752.9 KB


In [9]:
X = year.drop(columns=['GHI'])
Y = year.pop('GHI')

transformer = Normalizer().fit(X)
X_norm = transformer.transform(X)


print(transformer)
print(X_norm)

seed = 7
test_size = 0.33
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=test_size, random_state=seed)
model = XGBClassifier()

Normalizer(copy=True, norm='l2')
[[0.         0.00408625 0.0130263  ... 0.         0.07548294 0.00452638]
 [0.         0.00613678 0.01247493 ... 0.         0.07681474 0.00455494]
 [0.         0.00717292 0.01209779 ... 0.         0.076098   0.0044426 ]
 ...
 [0.         0.         0.01546334 ... 0.         0.06476746 0.00437793]
 [0.         0.00102765 0.01465211 ... 0.         0.06889262 0.00445176]
 [0.         0.00204918 0.01382877 ... 0.         0.07267697 0.00448728]]


In [10]:
model.fit(X_train, y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
       colsample_bytree=1, gamma=0, learning_rate=0.1, max_delta_step=0,
       max_depth=3, min_child_weight=1, missing=None, n_estimators=100,
       n_jobs=1, nthread=None, objective='multi:softprob', random_state=0,
       reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
       silent=True, subsample=1)

In [11]:
y_pred = model.predict(X_test)



In [ ]:
from collections import Counter

predictions = [value for value in y_pred]
print(len(y_test))
# predictions = [round(value) for value in y_pred]
accuracy = accuracy_score(y_test, predictions)
print("Accuracy: %.2f%%" % (accuracy * 100.0))

In [ ]:
mean_squared_error(y_true, y_pred)

In [12]:
print(y_pred)

[156. 853.   0. ... 262. 396. 663.]


In [15]:
y_for_rmse = []
for i in y_test:
    y_for_rmse.append(i)

In [17]:
mean_squared_error(y_for_rmse, y_pred)

8050.114147353856